spring:
  resources:
      static-locations: file:${ftp.home-dir}
  mvc:
    static-path-pattern: /res/**
server:
  host: localhost # This should be your server's real IP
  port: 8080
logging:
  level:
    root: info
    com.ajavac: debug
  file: spring.log
ftp:
  port: 2121
  passive-ports:
  username: admin
  password: admin
  home-dir: res/