spring:
  profiles:
    active:
server:
  host: localhost
  port: 8080
logging:
  level:
    root: info
    com.ajavac: debug
  file: spring.log
ftp:
  port: 2121
  passive-ports: 23300-23399
  username: admin
  password: admin
  home-dir: home